<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVl9xgel\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVl9xgel/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVl9xgel.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVl9xgel\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVl9xgel\appProdProjectContainer([
    'container.build_hash' => 'Vl9xgel',
    'container.build_id' => '981f85b2',
    'container.build_time' => 1627983462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVl9xgel');
